version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: db_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'

  api:
    build: ./borg-project/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./borg-project:/app
    ports:
      - 8000:8000
    env_file:
      - ./borg-project/.env
    depends_on:
      - db
      - redis
      - redis-commander

volumes:
  cache:
  db-data:
